"""empty message

Revision ID: 1b7c4a738b0a
Revises: 3729f134fe4c
Create Date: 2021-09-06 21:02:29.524519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7c4a738b0a'
down_revision = '3729f134fe4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
